### PR TITLE
2017/06/ddorman

### PR DESCRIPTION
**Pull request by dandorman**
Another one where the instrumented tests got "stuck" in CLJS.

### CODE REVIEW

**Comment by borkdude** [comment]
FWIW, my day 6 finishes within 11 seconds on CLJS with optimizations advanced and 24 with optimizations none. Under advanced I found a bug in CLJS spec which is about to be fixed: https://dev.clojure.org/jira/browse/CLJS-2995
One way to speed up this puzzle is to re-use the result from part-1 in part-2.

**Comment by borkdude** [comment]
@dandorman I made some changes to the config options. See the README.

E.g. you can skip CLJS with:

    INSTRUMENT=true SKIP_CLJS=true script/test-one ...

**Comment by dandorman** [comment]
Excellent! Those options should be handy.

I haven't been terribly worried about speed, because when I was running the tests with `UNSTRUMENT=1` (which I assume has been superseded by `INSTRUMENT`), the performance in CLJS has been comparable with that of CLJ. It appears to be something that happens with instrumentation turned on.

**Comment by borkdude** [comment]
Right. That's why I have chosen to rename this repo to advent-of-cljc. Instrumenting using core specs is optional since it's a bit experimental considering the list of issues I've encountered with it.

**Pull request merged**
